server:
  port: 8001

spring:
  application:
    name: consumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 23456789
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sise.entities
